#!/bin/bash

TARGET=$1
TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")
HTML_REPORT="securecheck_$TIMESTAMP.html"
PDF_REPORT="securecheck_$TIMESTAMP.pdf"

# HTML Report Template
cat <<EOF > $HTML_REPORT
<html>
<head>
  <meta charset="utf-8">
  <title>Security Report - $TARGET</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; }
    h1 { color: #1F618D; }
    h2 { color: #148F77; }
    pre { background-color: #F8F9F9; padding: 10px; border: 1px solid #ccc; overflow-x: auto; }
    .footer { font-size: 12px; color: #888; margin-top: 40px; text-align: center; }
  </style>
</head>
<body>
  <h1>🔒 SecureCheck - Security Scan Report</h1>
  <p><strong>Target:</strong> $TARGET</p>
  <p><strong>Generated by:</strong> Ali Belalia – <a href="mailto:iloveyoubelben@gmail.com">iloveyoubelben@gmail.com</a></p>
  <p><em>Quick security scan to protect your digital presence</em></p>
  <hr>
EOF

# WHOIS
echo "<h2>1. WHOIS Information</h2><pre>" >> $HTML_REPORT
whois $TARGET 2>/dev/null | head -n 50 >> $HTML_REPORT
echo "</pre>" >> $HTML_REPORT

# Nmap
echo "<h2>2. Open Ports Scan (Nmap)</h2><pre>" >> $HTML_REPORT
nmap -T4 -F $TARGET 2>/dev/null >> $HTML_REPORT
echo "</pre>" >> $HTML_REPORT

# SSL
echo "<h2>3. SSL Certificate Info</h2><pre>" >> $HTML_REPORT
echo | openssl s_client -connect $TARGET:443 -servername $TARGET 2>/dev/null | openssl x509 -noout -text | head -n 30 >> $HTML_REPORT
echo "</pre>" >> $HTML_REPORT

# HTTP Headers
echo "<h2>4. HTTP Response Headers</h2><pre>" >> $HTML_REPORT
curl -I -L --max-redirs 3 --connect-timeout 5 https://$TARGET 2>/dev/null >> $HTML_REPORT
echo "</pre>" >> $HTML_REPORT

# Footer
cat <<EOF >> $HTML_REPORT
  <div class="footer">
    Report generated using Kali Linux – SecureCheck by Ali Belalia
  </div>
</body>
</html>
EOF

# Convert to PDF
wkhtmltopdf $HTML_REPORT $PDF_REPORT > /dev/null 2>&1

# Done
echo "[+] ✅ Report generated successfully: $PDF_REPORT"
